### ISSUE TITLE
Use Csec logo

### ISSUE THREAD

**Issue by shaharyar-shamshi** [CSEC-NITH/csec-website-new#4]
In every page at the top left corner add csec logo as there is logo on Facebook

**Comment by vishichoudhary** [comment]
Yeah that's great :-)

**Comment by srbcheema1** [comment]
@shaharyar-shamshi please provide some description so that it may guide juniors where to add, you can provide filename or location to add the logo. Some juniors were asking questions regarding where to add. so providing a description may be helpful to them

you can also add label "Hacktoberfest" to it.
